apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: pull-request
spec:
  type: pullRequest
  params:
  - name: url
    value: https://github.com/mnuttall/gitops-example-dev/pull/22
  secrets:
   - fieldName: authToken
     secretName: github-secrets
     secretKey: token