apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: automerge-pipeline
spec:
  params:
  - name: github-secret
    type: string
  - name: github-config
    type: string
  resources: 
  - name: source-repo
    type: git
  - name: pr
    type: pullRequest
  tasks:
  - name: do-this-first
    taskRef:
      name: automerge-task
    resources:
      inputs:
      - name: git-source
        resource: source-repo
      - name: pull-request
        resource: pr
    params:
    - name: github-secret
      value: $(params.github-secret)
    - name: github-config
      value: $(params.github-config)